# Generated by Django 4.0.4 on 2022-06-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='games/image/')),
                ('title', models.CharField(max_length=200, verbose_name='Название игры')),
            ],
            options={
                'verbose_name': 'Игру',
                'verbose_name_plural': 'Игры',
            },
        ),
    ]
